# Generated by Django 3.1.1 on 2020-10-17 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import placeToEat.api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceToEat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('institution_type', models.IntegerField(choices=[(1, 'Ethnic'), (2, 'FastFood'), (3, 'Pub'), (4, 'Cafe'), (5, 'Restaurant')], default=placeToEat.api.models.InstitutionTypes['Restaurant'])),
                ('rating', models.IntegerField(choices=[(1, 'ONE_STAR'), (2, 'TWO_STAR'), (3, 'THREE_STAR'), (4, 'FOUR_STAR'), (5, 'FIVE_STAR')], default=placeToEat.api.models.RatingTypes['FIVE_STAR'])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
