# Generated by Django 3.1.1 on 2020-09-24 10:48

from django.db import migrations, models
import placeToEat.api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceToEat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('institution_type', models.IntegerField(choices=[(1, 'Ethnic'), (2, 'FastFood'), (3, 'Pub'), (4, 'Cafe'), (5, 'Restaurant')], default=placeToEat.api.models.InstitutionTypes['Restaurant'])),
                ('rating', models.IntegerField(choices=[(1, 'ONE_STAR'), (2, 'TWO_STAR'), (3, 'THREE_STAR'), (4, 'FOUR_STAR'), (5, 'FIVE_STAR')], default=placeToEat.api.models.RatingTypes['FIVE_STAR'])),
            ],
        ),
    ]
