# Generated by Django 3.1.1 on 2020-09-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='room',
            field=models.IntegerField(),
        ),
    ]
