# Generated by Django 3.1.1 on 2020-09-22 19:32

from django.db import migrations, models
import pointOfInterest.api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price_to_visit', models.FloatField(max_length=100)),
                ('images_links', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, 'ONE_STAR'), (2, 'TWO_STAR'), (3, 'THREE_STAR'), (4, 'FOUR_STAR'), (5, 'FIVE_STAR')], default=pointOfInterest.api.models.RatingTypes['FIVE_STAR'])),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
