# Generated by Django 3.1.1 on 2020-10-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='fk_accommodation',
        ),
        migrations.RemoveField(
            model_name='country',
            name='fk_placeToEat',
        ),
        migrations.RemoveField(
            model_name='country',
            name='fk_pointOfInterest',
        ),
        migrations.RemoveField(
            model_name='country',
            name='fk_transport',
        ),
    ]
