# Generated by Django 3.1.3 on 2020-11-05 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import transport.api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transportation_type', models.IntegerField(choices=[(1, 'Plane'), (2, 'Ship'), (3, 'Bus'), (4, 'Train'), (5, 'Car'), (6, 'ByFoot'), (7, 'Bicycle')], default=transport.api.models.TransportationTypes['Plane'])),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('date_available', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
